In [1]:
import pandas as pd

from nltk.tokenize import word_tokenize

In [3]:
data = pd.read_csv("new_data.csv")
data.head()

           label                                            message
0           work  Please review the quarterly financial report t...
1           spam       Claim your free shopping voucher immediately
2  advertisement         Buy stylish sunglasses with huge discounts
3           work        The client meeting has been moved to Monday
4           spam               You won free movie tickets click now

In [11]:
data["message"] = data["message"].str.lower()

In [12]:
data.head()

           label                                            message
0           work  please review the quarterly financial report t...
1           spam       claim your free shopping voucher immediately
2  advertisement         buy stylish sunglasses with huge discounts
3           work        the client meeting has been moved to monday
4           spam               you won free movie tickets click now

In [13]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [18]:
data["punctuation_remove"] = data["message"].str.translate(str.maketrans('', '', string.punctuation))
data.head(10)

,label,message,punctuation_remove
0,work,please review the quarterly financial report t...,please review the quarterly financial report t...
1,spam,claim your free shopping voucher immediately,claim your free shopping voucher immediately
2,advertisement,buy stylish sunglasses with huge discounts,buy stylish sunglasses with huge discounts
3,work,the client meeting has been moved to monday,the client meeting has been moved to monday
4,spam,you won free movie tickets click now,you won free movie tickets click now
5,advertisement,upgrade your laptop with latest technology,upgrade your laptop with latest technology
6,work,complete the machine learning assignment befor...,complete the machine learning assignment befor...
7,advertisement,join our online yoga classes today,join our online yoga classes today
8,spam,exclusive reward waiting for your confirmation,exclusive reward waiting for your confirmation
9,work,please submit the employee attendance sheet,please submit the employee attendance sheet

In [23]:
from nltk.tokenize import word_tokenize
data["tokenized_words"] = data["punctuation_remove"].apply(word_tokenize)
data.head()

,label,message,punctuation_remove,tokenized_words
0,work,please review the quarterly financial report t...,please review the quarterly financial report t...,"[please, review, the, quarterly, financial, re..."
1,spam,claim your free shopping voucher immediately,claim your free shopping voucher immediately,"[claim, your, free, shopping, voucher, immedia..."
2,advertisement,buy stylish sunglasses with huge discounts,buy stylish sunglasses with huge discounts,"[buy, stylish, sunglasses, with, huge, discounts]"
3,work,the client meeting has been moved to monday,the client meeting has been moved to monday,"[the, client, meeting, has, been, moved, to, m..."
4,spam,you won free movie tickets click now,you won free movie tickets click now,"[you, won, free, movie, tickets, click, now]"

In [24]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
print(stop_words)

{"won't", 'which', "needn't", 'about', 'own', 'through', 'only', 'needn', 'just', 'any', "shan't", 'such', 'with', 'those', 'more', 'by', 'do', 'aren', 'are', 'down', 'hasn', 'isn', "he'd", 'itself', 'our', 'she', "we'll", "we've", 'doing', 'against', "wouldn't", "he'll", 'he', 's', 'where', 'at', 'y', 'ours', 'll', 'an', "you'd", 'further', 'being', "it'd", "shouldn't", 'too', 're', 'so', "don't", "hadn't", 'your', "haven't", 'weren', 'up', 'this', 'most', "she'll", 'am', 'was', 'his', 'you', 't', 'than', 'some', 'between', 'himself', 'my', 'other', 'into', 'shouldn', 'me', 'until', 'ma', "you're", "weren't", 'not', "i've", 'have', 'd', 'of', "they'd", "mustn't", 'be', 'few', 'that', 'all', 'i', 'o', 'has', 'does', 'from', 'in', 'for', "they've", "we're", 'didn', 'couldn', 'or', 'again', 'to', 'how', 'myself', 'ain', 'wouldn', 'during', 'it', 'there', "didn't", 'before', "i'm", 'these', "you'll", 'and', 'they', 'but', 'should', 'yourselves', 'what', "doesn't", "you've", "she's", 'her', 'off', 'whom', 'yours', 'its', 'were', 'hers', "i'll", 'as', 'each', "isn't", 'won', 'a', "it's", 'below', 'theirs', 'mightn', "that'll", 'both', 'very', 'having', 'while', "it'll", 'if', 'nor', 'same', 've', 'been', "they'll", 'above', 'now', 'we', 'haven', 'yourself', "he's", 'mustn', 'no', 'will', 'why', 'who', 'because', 'here', "we'd", 'when', 'then', "should've", 'is', 'm', "she'd", 'herself', "mightn't", 'themselves', "i'd", 'them', 'on', 'under', 'can', 'hadn', "wasn't", "they're", 'the', "couldn't", 'their', 'out', 'after', 'did', 'shan', 'ourselves', 'don', "hasn't", 'him', "aren't", 'had', 'doesn', 'once', 'over', 'wasn'}

In [26]:
data["stopword_remove"] = data['tokenized_words'].apply(
    lambda words: [ word for word in words if word not in stop_words]
)
data.head()

,label,message,punctuation_remove,tokenized_words,stopword_remove
0,work,please review the quarterly financial report t...,please review the quarterly financial report t...,"[please, review, the, quarterly, financial, re...","[please, review, quarterly, financial, report,..."
1,spam,claim your free shopping voucher immediately,claim your free shopping voucher immediately,"[claim, your, free, shopping, voucher, immedia...","[claim, free, shopping, voucher, immediately]"
2,advertisement,buy stylish sunglasses with huge discounts,buy stylish sunglasses with huge discounts,"[buy, stylish, sunglasses, with, huge, discounts]","[buy, stylish, sunglasses, huge, discounts]"
3,work,the client meeting has been moved to monday,the client meeting has been moved to monday,"[the, client, meeting, has, been, moved, to, m...","[client, meeting, moved, monday]"
4,spam,you won free movie tickets click now,you won free movie tickets click now,"[you, won, free, movie, tickets, click, now]","[free, movie, tickets, click]"

In [27]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [29]:
data["stemmed_words"] = data["stopword_remove"].apply(
    lambda words: [stemmer.stem(word)for word in words]
)

data.head()

,label,message,punctuation_remove,tokenized_words,stopword_remove,stemmed_words
0,work,please review the quarterly financial report t...,please review the quarterly financial report t...,"[please, review, the, quarterly, financial, re...","[please, review, quarterly, financial, report,...","[pleas, review, quarterli, financi, report, to..."
1,spam,claim your free shopping voucher immediately,claim your free shopping voucher immediately,"[claim, your, free, shopping, voucher, immedia...","[claim, free, shopping, voucher, immediately]","[claim, free, shop, voucher, immedi]"
2,advertisement,buy stylish sunglasses with huge discounts,buy stylish sunglasses with huge discounts,"[buy, stylish, sunglasses, with, huge, discounts]","[buy, stylish, sunglasses, huge, discounts]","[buy, stylish, sunglass, huge, discount]"
3,work,the client meeting has been moved to monday,the client meeting has been moved to monday,"[the, client, meeting, has, been, moved, to, m...","[client, meeting, moved, monday]","[client, meet, move, monday]"
4,spam,you won free movie tickets click now,you won free movie tickets click now,"[you, won, free, movie, tickets, click, now]","[free, movie, tickets, click]","[free, movi, ticket, click]"

In [31]:
data["final_text"] = data["stemmed_words"].apply(
    lambda words: " ".join(words)
)
data.head()

,label,message,punctuation_remove,tokenized_words,stopword_remove,stemmed_words,final_text
0,work,please review the quarterly financial report t...,please review the quarterly financial report t...,"[please, review, the, quarterly, financial, re...","[please, review, quarterly, financial, report,...","[pleas, review, quarterli, financi, report, to...",pleas review quarterli financi report today
1,spam,claim your free shopping voucher immediately,claim your free shopping voucher immediately,"[claim, your, free, shopping, voucher, immedia...","[claim, free, shopping, voucher, immediately]","[claim, free, shop, voucher, immedi]",claim free shop voucher immedi
2,advertisement,buy stylish sunglasses with huge discounts,buy stylish sunglasses with huge discounts,"[buy, stylish, sunglasses, with, huge, discounts]","[buy, stylish, sunglasses, huge, discounts]","[buy, stylish, sunglass, huge, discount]",buy stylish sunglass huge discount
3,work,the client meeting has been moved to monday,the client meeting has been moved to monday,"[the, client, meeting, has, been, moved, to, m...","[client, meeting, moved, monday]","[client, meet, move, monday]",client meet move monday
4,spam,you won free movie tickets click now,you won free movie tickets click now,"[you, won, free, movie, tickets, click, now]","[free, movie, tickets, click]","[free, movi, ticket, click]",free movi ticket click

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X = tfidf.fit_transform(data["final_text"])

In [ ]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 249 stored elements and shape (50, 186)>
  Coords	Values
  (0, 114)	0.34278371390390283
  (0, 135)	0.43732100651709344
  (0, 126)	0.43732100651709344
  (0, 57)	0.43732100651709344
  (0, 131)	0.43732100651709344
  (0, 167)	0.34278371390390283
  (1, 20)	0.4058202463341888
  (1, 61)	0.35941085449771154
  (1, 146)	0.48515762570340076
  (1, 180)	0.48515762570340076
  (1, 74)	0.48515762570340076
  (2, 14)	0.425483383019197
  (2, 157)	0.470489661149167
  (2, 160)	0.470489661149167
  (2, 73)	0.470489661149167
  (2, 39)	0.39355092050427926
  (3, 24)	0.47428614502497035
  (3, 95)	0.47428614502497035
  (3, 102)	0.524454624002261
  (3, 100)	0.524454624002261
  (4, 61)	0.4110245589802905
  (4, 103)	0.5548293732512601
  (4, 165)	0.5548293732512601
  (4, 23)	0.464098637220888
  (5, 174)	0.5
  :	:
  (45, 118)	0.42853048986156134
  (45, 91)	0.42853048986156134
  (45, 11)	0.47385908125572046
  (45, 71)	0.47385908125572046
  (46, 117)	0.42853048986156134
  (46, 116)	0.42853048986156134
  (46, 36)	0.42853048986156134
  (46, 105)	0.47385908125572046
  (46, 168)	0.47385908125572046
  (47, 8)	0.37282959686270606
  (47, 115)	0.42097170117733057
  (47, 153)	0.42097170117733057
  (47, 123)	0.503271172092601
  (47, 175)	0.503271172092601
  (48, 39)	0.39355092050427926
  (48, 125)	0.425483383019197
  (48, 63)	0.470489661149167
  (48, 1)	0.470489661149167
  (48, 55)	0.470489661149167
  (49, 173)	0.3621340356874466
  (49, 34)	0.391517352858063
  (49, 36)	0.391517352858063
  (49, 142)	0.4329308124164697
  (49, 79)	0.4329308124164697
  (49, 56)	0.4329308124164697

In [37]:
tfidf_array = X.toarray()
tfidf

TfidfVectorizer()

In [39]:
tfidf_array.shape

(50, 186)

In [40]:
tfidf_array[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.43732101, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.34278371,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.43732101, 0.        , 0.        , 0.        ,
       0.        , 0.43732101, 0.        , 0.        , 0.        ,
       0.43732101, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.34278371, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [45]:
tfidf.get_feature_names_out()

array(['abroad', 'accessori', 'account', 'activ', 'afford', 'analysi',
       'assign', 'attend', 'avail', 'bakeri', 'bonu', 'book', 'burger',
       'busi', 'buy', 'card', 'cash', 'cashback', 'casino', 'center',
       'claim', 'class', 'clean', 'click', 'client', 'complet', 'confirm',
       'congratul', 'custom', 'data', 'dataset', 'deadlin', 'delici',
       'deliveri', 'depart', 'deploy', 'detail', 'develop', 'directli',
       'discount', 'discov', 'discuss', 'document', 'draw', 'employe',
       'enjoy', 'excel', 'excit', 'exclus', 'expert', 'expir', 'explor',
       'farm', 'fashion', 'featur', 'festiv', 'financ', 'financi',
       'finish', 'fit', 'food', 'free', 'fresh', 'game', 'get', 'gift',
       'glow', 'health', 'healthi', 'holiday', 'home', 'hotel', 'hr',
       'huge', 'immedi', 'industri', 'instant', 'interview', 'inventori',
       'invoic', 'issu', 'item', 'join', 'laptop', 'latest', 'learn',
       'limit', 'link', 'lotteri', 'low', 'lucki', 'luxuri', 'machin',
       'manag', 'market', 'meet', 'membership', 'midnight', 'model',
       'modif', 'monday', 'monthli', 'move', 'movi', 'music', 'note',
       'number', 'offer', 'offic', 'onlin', 'order', 'organ', 'packag',
       'perform', 'pleas', 'premium', 'prepar', 'present', 'price',
       'prize', 'product', 'program', 'project', 'promot', 'propos',
       'purchas', 'quarterli', 'receiv', 'recharg', 'record', 'regist',
       'report', 'request', 'resolv', 'restaur', 'review', 'revis',
       'reward', 'sale', 'schedul', 'secur', 'select', 'send', 'server',
       'session', 'sheet', 'shop', 'skin', 'skincar', 'slide', 'smart',
       'smartphon', 'softwar', 'special', 'start', 'strategi', 'stream',
       'stylish', 'submit', 'subscrib', 'sunglass', 'support', 'team',
       'technic', 'technolog', 'ticket', 'time', 'today', 'tomorrow',
       'track', 'train', 'travel', 'unlimit', 'updat', 'upgrad', 'user',
       'vacat', 'veget', 'verif', 'verifi', 'voucher', 'wait', 'watch',
       'win', 'yearli', 'yoga'], dtype=object)

In [48]:
tfidf.get_feature_names_out()[114]

'pleas'

In [49]:
data["label"] = data["label"].map({
    "spam":0,
    "work":1,
    "advertisement":2
})

In [50]:
y = data["label"]

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [52]:
print(X_train.shape)
print(X_test.shape)

(40, 186)
(10, 186)

In [53]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

In [54]:
model.fit(X_train, y_train)

MultinomialNB()

In [55]:
y_pred = model.predict(X_test)

In [59]:
result = pd.DataFrame({
    
    "Actual": y_test,
    
    "Predicted": y_pred
})
result.head(50)

    Actual  Predicted
13       2          1
39       2          1
30       2          1
45       2          0
17       0          0
48       2          2
26       0          0
25       1          1
32       0          0
19       1          1

In [60]:
label_map = {

    0:"spam",
    
    1:"work",
    
    2:"advertisement"
}

In [61]:
result["Actual"] = result["Actual"].map(label_map)

result["Predicted"] = result["Predicted"].map(label_map)

In [62]:
result.head(10)

           Actual      Predicted
13  advertisement           work
39  advertisement           work
30  advertisement           work
45  advertisement           spam
17           spam           spam
48  advertisement  advertisement
26           spam           spam
25           work           work
32           spam           spam
19           work           work

In [63]:
comparison = pd.DataFrame({

    "Message": data.iloc[y_test.index]["message"],

    "Actual": y_test,

    "Predicted": y_pred
})

In [64]:
comparison["Actual"] = comparison["Actual"].map(label_map)

comparison["Predicted"] = comparison["Predicted"].map(label_map)

In [65]:
comparison.head(10)

,Message,Actual,Predicted
13,travel abroad with affordable holiday packages,advertisement,work
39,order fresh vegetables directly from farms,advertisement,work
30,buy smart watches with health tracking features,advertisement,work
45,book luxury hotels at affordable prices,advertisement,spam
17,get free recharge by clicking this secure link,spam,spam
48,purchase gaming accessories with festive disco...,advertisement,advertisement
26,free gift cards available for selected customers,spam,spam
25,please organize the office inventory records,work,work
32,claim your bonus reward before it expires,spam,spam
19,prepare monthly performance analysis for manager,work,work

In [66]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.6

In [70]:
probability = model.predict_proba(X_test)
print(probability)

[[0.3316069  0.35911129 0.3092818 ]
 [0.31733286 0.34365331 0.33901383]
 [0.31819627 0.34250636 0.33929737]
 [0.35646029 0.32094037 0.32259933]
 [0.44966783 0.29477596 0.25555621]
 [0.28878189 0.31276856 0.39844955]
 [0.45388539 0.26816173 0.27795289]
 [0.28618774 0.4057819  0.30803036]
 [0.53535646 0.25057989 0.21406366]
 [0.29644548 0.42706814 0.27648637]]

In [73]:
confidence = probability.max(axis=1)
confidence = confidence * 100


comparison = pd.DataFrame({

    "Message": data.iloc[y_test.index]["message"],

    "Actual": y_test,

    "Predicted": y_pred,

    "Confidence %": confidence
})

In [74]:
label_map = {

    0:"spam",

    1:"work",

    2:"advertisement"
}

comparison["Actual"] = comparison["Actual"].map(label_map)

comparison["Predicted"] = comparison["Predicted"].map(label_map)

In [75]:
comparison["Confidence %"] = comparison["Confidence %"].round(2)

In [76]:
comparison.head(10)

,Message,Actual,Predicted,Confidence %
13,travel abroad with affordable holiday packages,advertisement,work,35.91
39,order fresh vegetables directly from farms,advertisement,work,34.37
30,buy smart watches with health tracking features,advertisement,work,34.25
45,book luxury hotels at affordable prices,advertisement,spam,35.65
17,get free recharge by clicking this secure link,spam,spam,44.97
48,purchase gaming accessories with festive disco...,advertisement,advertisement,39.84
26,free gift cards available for selected customers,spam,spam,45.39
25,please organize the office inventory records,work,work,40.58
32,claim your bonus reward before it expires,spam,spam,53.54
19,prepare monthly performance analysis for manager,work,work,42.71