India Road accident of 2018

In [4]:
#Import File Handling Module
import pandas as pd

In [7]:
data_set = pd.read_csv("AccidentsBig.csv")
data_set.head()#Display First 5 Rows of the Data Set

C:\Users\Abcom\AppData\Local\Temp\ipykernel_12132\2658656049.py:1: DtypeWarning: Columns (8,10,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set = pd.read_csv("AccidentsBig.csv")

,Accident_Index,longitude,latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Day_of_Week,Time,Local_Authority_(District),...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Date
0,1.0,78.610393,14.724026,1.0,2.0,1.0,1.0,3.0,17:42,12.0,...,1.0,1.0,2.0,2.0,0.0,0.0,1.0,1.0,E01002849,04-01-2018
1,2.0,78.534042,14.762353,1.0,3.0,1.0,1.0,4.0,17:36,12.0,...,5.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002909,05-01-2018
2,3.0,78.470877,14.745606,1.0,3.0,2.0,1.0,5.0,00:15,12.0,...,0.0,4.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002857,06-01-2018
3,4.0,78.557994,14.667128,1.0,3.0,1.0,1.0,6.0,10:35,12.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,E01002840,07-01-2018
4,5.0,78.576431,14.703443,1.0,3.0,1.0,1.0,2.0,21:13,12.0,...,0.0,7.0,1.0,2.0,0.0,0.0,1.0,1.0,E01002863,10-01-2018

In [8]:
data_set.info()#Get Information about the Data Set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Accident_Index                               59998 non-null  float64
 1   longitude                                    59998 non-null  float64
 2   latitude                                     59998 non-null  float64
 3   Police_Force                                 59998 non-null  float64
 4   Accident_Severity                            59998 non-null  float64
 5   Number_of_Vehicles                           59998 non-null  float64
 6   Number_of_Casualties                         59998 non-null  float64
 7   Day_of_Week                                  59998 non-null  float64
 8   Time                                         59997 non-null  object
 9   Local_Authority_(District)                   59998 non-null  float64
 10  Local_Authority_(Highway)                    59998 non-null  object
 11  1st_Road_Class                               59998 non-null  float64
 12  1st_Road_Number                              59998 non-null  float64
 13  Road_Type                                    59998 non-null  float64
 14  Speed_limit                                  59998 non-null  float64
 15  Junction_Detail                              59998 non-null  float64
 16  Junction_Control                             59998 non-null  float64
 17  2nd_Road_Class                               59998 non-null  float64
 18  2nd_Road_Number                              59998 non-null  float64
 19  Pedestrian_Crossing-Human_Control            59998 non-null  float64
 20  Pedestrian_Crossing-Physical_Facilities      59998 non-null  float64
 21  Light_Conditions                             59998 non-null  float64
 22  Weather_Conditions                           59998 non-null  float64
 23  Road_Surface_Conditions                      59998 non-null  float64
 24  Special_Conditions_at_Site                   59998 non-null  float64
 25  Carriageway_Hazards                          59998 non-null  float64
 26  Urban_or_Rural_Area                          59998 non-null  float64
 27  Did_Police_Officer_Attend_Scene_of_Accident  59998 non-null  float64
 28  LSOA_of_Accident_Location                    59901 non-null  object
 29  Date                                         59998 non-null  object
dtypes: float64(26), object(4)
memory usage: 240.0+ MB

In [14]:
info_df = pd.DataFrame({
    "Column_Name": data_set.columns,
    "Non_Null_Count": data_set.notnull().sum().values,
    "Null_Count": data_set.isnull().sum().values,
    "Dtype": data_set.dtypes.values
})
info_df

,Column_Name,Non_Null_Count,Null_Count,Dtype
0,Accident_Index,59998,988577,float64
1,longitude,59998,988577,float64
2,latitude,59998,988577,float64
3,Police_Force,59998,988577,float64
4,Accident_Severity,59998,988577,float64
5,Number_of_Vehicles,59998,988577,float64
6,Number_of_Casualties,59998,988577,float64
7,Day_of_Week,59998,988577,float64
8,Time,59997,988578,object
9,Local_Authority_(District),59998,988577,float64
10,Local_Authority_(Highway),59998,988577,object
11,1st_Road_Class,59998,988577,float64
12,1st_Road_Number,59998,988577,float64
13,Road_Type,59998,988577,float64
14,Speed_limit,59998,988577,float64
15,Junction_Detail,59998,988577,float64
16,Junction_Control,59998,988577,float64
17,2nd_Road_Class,59998,988577,float64
18,2nd_Road_Number,59998,988577,float64
19,Pedestrian_Crossing-Human_Control,59998,988577,float64
20,Pedestrian_Crossing-Physical_Facilities,59998,988577,float64
21,Light_Conditions,59998,988577,float64
22,Weather_Conditions,59998,988577,float64
23,Road_Surface_Conditions,59998,988577,float64
24,Special_Conditions_at_Site,59998,988577,float64
25,Carriageway_Hazards,59998,988577,float64
26,Urban_or_Rural_Area,59998,988577,float64
27,Did_Police_Officer_Attend_Scene_of_Accident,59998,988577,float64
28,LSOA_of_Accident_Location,59901,988674,object
29,Date,59998,988577,object